# Generated by Django 5.2.8 on 2025-12-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_description_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sidebar_start_key',
            field=models.CharField(blank=True, help_text="Exact text in sidebar to START (e.g. 'C++ Tutorial')", max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='sidebar_stop_keys',
            field=models.CharField(blank=True, help_text="Comma separated text to STOP (e.g. 'File Handling, Reference')", max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='source_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.w3schools.com/cpp/'),
        ),
    ]
