# Generated by Django 5.2.8 on 2026-06-25 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="e.g., 'about', 'privacy', 'terms'", unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='{} Learnify', max_length=100)),
                ('footer_description', models.TextField(default='Empowering developers worldwide with project-based learning.')),
                ('github_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('contact_email', models.EmailField(default='support@learnify.com', max_length=254)),
                ('copyright_text', models.CharField(default='© 2026 Learnify. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
