# Generated by Django 5.2.8 on 2026-06-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_dynamicpage_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Platform', 'Students'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which the column appears')),
            ],
            options={
                'verbose_name_plural': 'Footer Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'About Us', 'Privacy Policy'", max_length=100)),
                ('url', models.CharField(blank=True, help_text="e.g., '/about' or 'https://google.com'", max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Order in which the link appears')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='courses.footercategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
